# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MeanTpopup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogMT(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(378, 212)
        Dialog.setStyleSheet("background-color: rgb(206, 232, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(200, 180, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.km = QtWidgets.QRadioButton(Dialog)
        self.km.setGeometry(QtCore.QRect(130, 50, 201, 17))
        self.km.setObjectName("km")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label.setObjectName("label")
        # self.label_2 = QtWidgets.QLabel(Dialog)
        # self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 16))
        # self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(128, 17, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("1e-12")
        # self.checkBox = QtWidgets.QCheckBox(Dialog)
        # self.checkBox.setGeometry(QtCore.QRect(200, 50, 70, 17))
        # self.checkBox.setText("")
        # self.checkBox.setObjectName("checkBox")
        self.trapezoid = QtWidgets.QRadioButton(Dialog)
        self.trapezoid.setGeometry(QtCore.QRect(130, 80, 201, 28))
        self.trapezoid.setObjectName("trapezoid")
        self.lamda = QtWidgets.QRadioButton(Dialog)
        self.lamda.setGeometry(QtCore.QRect(130, 110, 201, 28))
        self.lamda.setObjectName("simpson")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 111, 22))
        self.label_4.setObjectName("label_4")
        self.arithm = QtWidgets.QRadioButton(Dialog)
        self.arithm.setGeometry(QtCore.QRect(130, 140, 201, 28))
        self.arithm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.arithm.setObjectName("arithm")

        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select method for mean calculation"))
        self.km.setText(_translate("Dialog", "Kaplan Meier for Survival Analysis"))
        self.km.setChecked(True)
        self.label.setText(_translate("Dialog", "Compartment Volume"))
        #self.label_2.setText(_translate("Dialog", "Check to Use Stochastic Correction"))
        self.label_3.setText(_translate("Dialog", "Mean Survival Time"))
        self.trapezoid.setText(_translate("Dialog", "Trapezoid Rule for Histogram \n(for debug purposes only)"))
        self.lamda.setText(_translate("Dialog", "lamda"))
        self.label_4.setText(_translate("Dialog", "in Liters e.g. 4.574645e-23"))
        self.arithm.setText(_translate("Dialog", "Arithmetic mean of survival times\n(for debug purposes only)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DialogMT()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
